"""
Prompts package initialization
"""
from app.agent.prompts.investigation import (
    INVESTIGATION_SYSTEM_PROMPT,
    PLANNER_PROMPT_TEMPLATE,
    HYPOTHESES_PROMPT_TEMPLATE,
    VERIFICATION_PROMPT_TEMPLATE,
    ROOT_CAUSE_PROMPT_TEMPLATE,
)

__all__ = [
    "INVESTIGATION_SYSTEM_PROMPT",
    "PLANNER_PROMPT_TEMPLATE",
    "HYPOTHESES_PROMPT_TEMPLATE",
    "VERIFICATION_PROMPT_TEMPLATE",
    "ROOT_CAUSE_PROMPT_TEMPLATE",
]
