"""
Pydantic Schemas for LangGraph Agent Orchestrator

Defines structured Pydantic models for agent reasoning outputs:
- InvestigationPlan
- HypothesisItem & HypothesesPayload
- VerificationItem & VerificationPayload
- RootCauseResult
- API Request & Response models
"""
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Structured LLM Reasoning Schemas
# ---------------------------------------------------------------------------

class InvestigationPlan(BaseModel):
    """
    Structured investigation plan generated by the Planner node.
    """
    questions: List[str] = Field(
        ...,
        description="Core questions that must be answered to identify the root cause.",
    )
    required_tools: List[str] = Field(
        ...,
        description="Names of registered diagnostic tools needed to collect relevant telemetry.",
    )
    requires_rag: bool = Field(
        default=True,
        description="Whether organizational knowledge (runbooks, postmortems) should be retrieved.",
    )
    rag_queries: List[str] = Field(
        default_factory=list,
        description="Targeted search queries for knowledge base retrieval.",
    )
    reasoning: str = Field(
        ...,
        description="Explanation of the rationale behind the selected diagnostic approach.",
    )


class HypothesisItem(BaseModel):
    """
    Individual competing diagnostic hypothesis.
    """
    title: str = Field(..., description="Short title identifying the failure scenario.")
    description: str = Field(..., description="Detailed explanation of the causal mechanism.")
    confidence: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Initial confidence score between 0.0 and 1.0.",
    )
    supporting_evidence: List[str] = Field(
        default_factory=list,
        description="Summary of current evidence supporting this hypothesis.",
    )
    contradicting_evidence: List[str] = Field(
        default_factory=list,
        description="Summary of current evidence contradicting this hypothesis.",
    )


class HypothesesPayload(BaseModel):
    """
    Collection of competing hypotheses generated by the Hypotheses node.
    """
    hypotheses: List[HypothesisItem] = Field(
        ...,
        min_length=1,
        description="List of competing failure hypotheses.",
    )
    reasoning: str = Field(
        ...,
        description="Analytical reasoning linking incident context and evidence to hypotheses.",
    )


class VerificationItem(BaseModel):
    """
    Verification evaluation for a single hypothesis against empirical evidence.
    """
    hypothesis_title: str = Field(..., description="Title of the hypothesis evaluated.")
    status: str = Field(
        ...,
        description="Verification outcome: SUPPORTED, PARTIALLY_SUPPORTED, NOT_SUPPORTED, INCONCLUSIVE.",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Updated confidence score following evidence evaluation.",
    )
    evidence_summaries: List[str] = Field(
        default_factory=list,
        description="Key evidence summaries that decided this verification outcome.",
    )
    reasoning: str = Field(
        ...,
        description="Deductive reasoning comparing hypothesis claims against observed telemetry.",
    )


class VerificationPayload(BaseModel):
    """
    Aggregated verification results across all competing hypotheses.
    """
    verifications: List[VerificationItem] = Field(
        ...,
        description="Verification findings per hypothesis.",
    )
    need_more_evidence: bool = Field(
        default=False,
        description="Flag indicating if diagnostic ambiguity requires an additional tool execution cycle.",
    )
    additional_tools: List[str] = Field(
        default_factory=list,
        description="Additional diagnostic tools to invoke if more evidence is required.",
    )
    reasoning: str = Field(
        ...,
        description="High-level assessment of whether evidence is sufficient to conclude root cause.",
    )


class RootCauseResult(BaseModel):
    """
    Final root-cause determination synthesized by the Root Cause Analyzer node.
    """
    probable_root_cause: str = Field(
        ...,
        description="Synthesized root-cause statement reflecting empirical findings.",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Final confidence rating in the probable root cause.",
    )
    supporting_evidence: List[str] = Field(
        default_factory=list,
        description="Principal pieces of empirical evidence supporting this conclusion.",
    )
    alternative_explanations: List[str] = Field(
        default_factory=list,
        description="Alternative failure modes considered and reasons for lower likelihood.",
    )
    recommended_remediation: List[str] = Field(
        default_factory=list,
        description="Recommended non-executable recovery actions for human approval (Phase 7).",
    )
    reasoning: str = Field(
        ...,
        description="Comprehensive diagnostic synthesis explaining the full failure sequence.",
    )


# ---------------------------------------------------------------------------
# API Request & Response Models
# ---------------------------------------------------------------------------

class InvestigationRunRequest(BaseModel):
    """
    Request payload to trigger an automated investigation via the LangGraph agent.
    """
    max_iterations: Optional[int] = Field(
        default=5,
        ge=1,
        le=10,
        description="Maximum investigation feedback cycles before forced conclusion.",
    )


class InvestigationStepInfo(BaseModel):
    """Details of an individual investigation step recorded in the database."""
    step_order: int
    title: str
    status: str
    output_summary: Optional[str] = None
    created_at: datetime


class EvidenceInfo(BaseModel):
    """Details of an evidence item collected during the investigation."""
    id: uuid.UUID
    source_tool: str
    summary: str
    relevance_score: float
    raw_payload: Dict[str, Any]
    collected_at: datetime


class HypothesisInfo(BaseModel):
    """Details of an evaluated hypothesis persisted in the database."""
    id: uuid.UUID
    hypothesis_text: str
    status: str
    confidence_score: float
    supporting_evidence_ids: List[uuid.UUID]
    opposing_evidence_ids: List[uuid.UUID]
    created_at: datetime


class ToolCallInfo(BaseModel):
    """Details of an engineering tool call executed and persisted."""
    id: uuid.UUID
    tool_name: str
    arguments: Dict[str, Any]
    status: str
    execution_time_ms: int
    created_at: datetime


class InvestigationRunResponse(BaseModel):
    """
    Comprehensive structured response returned after running an agent investigation.
    """
    investigation_id: uuid.UUID
    incident_id: uuid.UUID
    investigation_number: str
    status: str
    probable_root_cause: Optional[str] = None
    confidence_score: Optional[float] = None
    analysis_reasoning: Optional[str] = None
    recommended_remediation: List[str] = Field(default_factory=list)
    steps: List[InvestigationStepInfo] = Field(default_factory=list)
    evidence: List[EvidenceInfo] = Field(default_factory=list)
    hypotheses: List[HypothesisInfo] = Field(default_factory=list)
    tool_calls: List[ToolCallInfo] = Field(default_factory=list)
    retrieved_sources: List[Dict[str, Any]] = Field(default_factory=list)
    created_at: datetime
    completed_at: Optional[datetime] = None
